### ISSUE TITLE
Add new site cho account bị lỗi

### ISSUE THREAD

**Issue by nemesisqp** [easywebhub/BackendEasyWeb#26]
@thanhtdvn check giúp xem Post data co gì sai không
`POST` `https://api.easywebhub.com/websites`
#### data
```json
{
	"Accounts" : [{
			"AccountId" : "bb59359b-bdb2-4d47-8a9c-8a25228446a8",
			"AccessLevel" : ["dev"],
			"WebsiteDisplayName": "some name"
		}
	],
	"Name" : "testttt",
	"DisplayName" : "testttt",
	"Url" : "http://qq:d65f1c188efa497d2e9d28f1ea83b42625b574b1ec7e98b02db1404a9882faf2@source.easywebhub.com/qq/testttt.git",
	"WebTemplateId": "1"
}
```
error
```
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Object reference not set to an instance of an object.",
  "ExceptionType": "System.NullReferenceException",
  "StackTrace": "   at ew.application.WebsiteManager.<>c.<CreateWebsite>b__8_0(AddWebsiteAccountDto x)\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at ew.application.WebsiteManager.CreateWebsite(CreateWebsiteDto dto)\r\n   at ew.webapi.Controllers.WebsiteController.CreateWebsite(CreateWebsiteDto dto)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}
```
#### stacktrace
````
at ew.application.WebsiteManager.<>c.<CreateWebsite>b__8_0(AddWebsiteAccountDto x)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ew.application.WebsiteManager.CreateWebsite(CreateWebsiteDto dto)
   at ew.webapi.Controllers.WebsiteController.CreateWebsite(CreateWebsiteDto dto)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
````

**Comment by thanhtdvn** [comment]
Do obj POST lên bị sai đó anh.

AccessLevels chớ ko phải AccessLevel

**Comment by nemesisqp** [comment]
ok, giờ ra response khác
```
{
  "Message": "CreateWebsite_NeedAnOwner"
}
```
có cần thêm param hay token gì không ta ?

**Comment by thanhtdvn** [comment]
Với lại em mới tạo thêm 1 API tạo website nằm ở area Account.
Mục đích của API này là khi user login app vào, user tạo website với quyền mặc định là **owner**

**POST** /users/{userId}/websites
``` json
{
  "Name": "string",
  "DisplayName": "string",
  "Url": "string",
  "WebTemplateId": "string"
}
```

Anh @nemesisqp, @vvthinh  nắm thông tin để cập nhật app nhé.

**Comment by nemesisqp** [comment]
ah sửa 
`"AccessLevels" : ["dev"]`
->
`"AccessLevels" : ["owner"]`
ok roi, đển chuyển sang sub url kia luôn

**Comment by thanhtdvn** [comment]
OKie a
